config/routes.rb
Rails.application.routes.draw do
  

  	devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
    }

    resources :repositories
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/repository.rb
class Repository < ApplicationRecord
  
  validates :name, :presence => {:message => "can't be blank"}
  validates :access_level, :presence => {:message => "can't be blank"}
  validates :description, :presence => {:message => "can't be blank"}


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :subdomain, :presence => {:message => "can't be blank"}

  after_create :create_tenant

  private

  def create_tenant
  	Apartment::Tenant.create(subdomain)
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:subdomain, :email, :password, :password_confirmation])
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController

	before_action :authenticate_user!
	before_filter :check_permission 

	def index
		@repositories = Repository.all
	end

	def new 
		@repository =  Repository.new
	end

	def create
		@repository =  Repository.new(repository_params)
		@repository.access_level = params[:access_level]

		if @repository.save
      flash[:notice] = "You have successfully created project"
      redirect_to repositories_path
    else
      render :new
    end


	end


	private

  def repository_params
    params.require(:repository).permit(:name, :access_level, :description)
  end

  def check_permission
  	if current_user.subdomain != request.subdomain
  		flash[:notice] = "Please login to your subdomain #{current_user.subdomain}.lvh.me"
  		sign_out current_user
		  redirect_to root_url
		end
  end



	
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        redirect_to repositories_path
        # respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        # respond_with resource, location: after_inactive_sign_up_path_for(resource)
        redirect_to repositories_path
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    # respond_with resource, location: after_sign_in_path_for(resource)
    redirect_to repositories_path
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/home/index.html.erb
	

<!-- <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Dynamic Gitlab</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><%#= link_to "Sign up", new_user_registration_path %></li>
      <li><%#= link_to "Log in", new_user_session_path %></li> 
    </ul>
  </div>
</nav> -->

	<div class="container bg">
    <div class="row">
    <a class="navbar-brand" href="#">welcome to Dynamic Gitlab</a>
    <div class="col-lg-6">
			<div class="text-center pull-right">	
				<% if current_user %>
		      Logged in as <%= current_user.email %>.
		      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
		    <% else %>
		      <%= link_to "Sign up", new_user_registration_path %> or
		      <%= link_to "Log in", new_user_session_path %>
		    <% end %>
	    </div>
	  </div>
	  </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DynamicGitlab</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p class="alert-info"><%= notice %></p>
    <p class="alert-warning"><%= alert %></p>
    <div id="user_nav">
    <%= yield %>
  </body>
</html>

app/views/repositories/index.html.erb
	<div class="container">
    <div class="row">
      <div class="col-sm-6" >
        <p><%=link_to "create project", new_repository_path %></p>
      </div>
      <div class="col-sm-6">
  			<div class="text-center pull-right">	
  				<% if current_user %>
  		      Logged in as <%= current_user.email %>.
  		      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  		    <% else %>
  		      <%= link_to "Sign up", new_user_registration_path %> or
  		      <%= link_to "Log in", new_user_session_path %>
  		    <% end %>
  	    </div>
  	  </div>
	  </div>
	  <!-- list  -->

    <%if @repositories.present? %>

      <div class="table-responsive">
        <h2>Your Repositories</h2>
        <p>These are your dynamic gitlab projects.</p>
        <table class="table">
          <thead>
            <tr>
              <th>Project name</th>
              <th>Visibility Level</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>

            <% @repositories.each_with_index do |repo, i| %>
              <tr class="<%= i%2==0 ? 'success' : 'danger' %>" >
                <td><%= repo.name %></td>
                <td><%= repo.access_level %></td>
                <td><%= repo.description %></td>
              </tr>
            <% end -%>

          </tbody>
        </table>
      </div>

    <%else%>
      <p>You have not created any project. </p>
    <% end -%>

</div>

app/views/repositories/new.html.erb
<%if @repository.errors.present? %>
<div class="alert alert-danger">
    <a class="close" data-dismiss="alert">×</a>
    <% @repository.errors.full_messages.each do |msg| %>
    <p><%=raw msg %></p>
    <% end %>
  </div>
<% end -%>

<div class="container">
  <div class="row">

      <h2>New Project</h2>

      <%= form_for @repository, url: repositories_path() do |f| %>

        <div class="field">
          <%= f.label :project_name %><br />
          <%= f.text_field :name, autofocus: true %>
        </div>

        
        
        <div class="field">
        <%= radio_button_tag(:access_level, "Private") %>
        <%= label_tag(:Private, "Private") %>
        </div>
        <div class="field">
        <%= radio_button_tag(:access_level, "Internal") %>
        <%= label_tag(:Internal, "Internal") %>
        </div>
        <div class="field">
        <%= radio_button_tag(:access_level, "Public") %>
        <%= label_tag(:Public, "Public") %>
        </div>


        <div class="field">
          <%= f.label :description %><br />
          <%= f.text_area :description %>
        </div>
        

        <div class="actions">
          <%= f.submit "Create" %>
        </div>
      <% end %>

  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%#= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>